# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - setup_remote_docker:
          version:17.09.0-ce
      - checkout
      - run: docker build -t bdb-basic-service-nodejs .

      - restore_cache:
        keys:
          - v1-dependencies-{{checksum "package.json"}}
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package.json"}}
      - run: yarn test